In [1]:
#第一章节:介绍tensor 和 variable
# https://pytorch-cn.readthedocs.io/zh/latest/package_references/torch-nn/    中文文档
import torch
import numpy as np
from torch.autograd import Variable

In [36]:
torch.Tensor([3])
np.array([3],dtype=np.float64)

array([3.])

In [4]:
#级别:np->tensor->variable
#variable.data=tensor tensor.data还是tensor    tensor.numpy()=np   variable没有.numpy()
#1.np转tensor
a=np.random.randn(2, 3)
tensor1 = torch.Tensor(a)
print(tensor1)


tensor([[-0.3809, -0.3181, -0.3212],
        [-0.2742, -2.1222,  0.9637]])


In [17]:
print('类型',type(tensor1))
print('维度:',tensor1.dim())
print('元素个数:',tensor1.numel)

类型 <class 'torch.Tensor'>
维度: 2
元素个数: <built-in method numel of Tensor object at 0x00000233AC9C0360>


In [24]:
#2.tensor 转np
b=tensor1.numpy()
print(b)
print(b.dtype)# np也有.dtype   tensor也有


[[-0.3809438  -0.31814507 -0.3212034 ]
 [-0.27416033 -2.1222126   0.96373165]]
float32


In [30]:
#3.  关于tensor
#https://pytorch-cn.readthedocs.io/zh/latest/package_references/Tensor/

#torch.FloatTensor()=torch.Tensor() 默认float32  可以放np, 也可以放int  [int]  list[[1,2],[3,4]]   torch.DoubleTensor() torch.IntTensor
xx=torch.Tensor([3]) #定义一个数3,
xx2=torch.Tensor(3) #定义3个常量
print("建立FloatTensor:",xx) 
print("建立FloatTensor:",xx2)

xx3=torch.Tensor(2,4).zero_()
print('xx3',xx3)
#print(xx3)

#torch.ones(3,2) 

x = torch.randn(3, 2)
print(x)
print(x.dtype)
print(x.type(torch.DoubleTensor))


# tensor 转化类型  x是tensor    tensor.float()   .int()   .long()
x=x.float()#浮点型32
print('转float',x.dtype)
print(x)
x=x.long()#整形#.int()
print('转long',x.dtype)
print(x)


建立FloatTensor: tensor([3.])
建立FloatTensor: tensor([-1105343071996124941766361088.0000,                             0.0000,
                                    0.0000])
xx3 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[ 1.2397,  0.9212],
        [-1.5091, -1.3504],
        [ 1.2199,  1.5377]])
torch.float32
tensor([[ 1.2397,  0.9212],
        [-1.5091, -1.3504],
        [ 1.2199,  1.5377]], dtype=torch.float64)
转float torch.float32
tensor([[ 1.2397,  0.9212],
        [-1.5091, -1.3504],
        [ 1.2199,  1.5377]])
转long torch.int64
tensor([[ 1,  0],
        [-1, -1],
        [ 1,  1]])


In [31]:
# tensor的计算  (tensor适用的variable也适用)
# 加法 +   
#      -
# torch.sum() 对整个矩阵求和，如果写上(S ,dim=0)，则沿着第0维度 对S矩阵 求和
# torch.t() 转置
# torch.mul(tensor1,tensor2) 对应元素相乘
# torch.mm(tensor1,tensor2)  横乘以竖
# 
torch.Tensor([3])+torch.Tensor([4])


tensor([7.])

In [ ]:
# 4 .variable 变量
# https://pytorch-cn.readthedocs.io/zh/latest/package_references/torch-autograd/
# 自动求导

# 从 tensor 转variable
# Variable(tensor, requires_grad=True)   #如果不写grad参数，默认False，说明这个variable不需要求导，作为常数用
#通常网络的输入数据就是false的variable     权重都是True的variable

# 定义
# 



# variable 属性
# variable.squeeze()  把维度为1 的维度去掉
# .view(3,-1) 维度转化用的
# 注意使用维度,如果要建立三维的（最外边为时间维），(时间，i , j )  第0维就是最外的维度
# .requires_grad 查询是否可导
# .is_leaf 是否叶子变量




# variable的求导问题
# 注意variable.data.numpy() 假设变量A=3，我们这样只是取出了3，变量里面的值，而不是取变量
# y=x^2+1  y.backward()   x.grad 求得y对x的导数
# 自己用Variable()创建的都叫做leaf variable 这种变量最好不要修改，还有禁止inplace操作 x=x+1 inplace
# 非leaf variable 指的是 (1)y=x+2  x是自己定义的variable y是凭空写的
#                        (2)y=x.clone()   此时y则为非叶子   非叶子都是可以修改赋值的
# 如果要改variable的值怎么办 参考   线性回归模型.py
# w.data = w.data - 1e-2 * w.grad.data # 手动更新 w   w是定义的variable， 这样就只改variable的数字，而不是改varialbe  而且可以inplace操作

# 如果想用高级的更新方法  如adam 等， 不想手动更新，则要这样定义W=nn.Parameter(tensor) b也是 然后写好数学公式  W就是variable
#nn.para就是把变量绑定到类nn.Module上，创建对象net之后,用optimizer(net.parameters())，就能对建立的nn.para进行更新了

# torch.mm(nn.Par,tensor)   第一参表示W，第二表示数据data
# optimizer = torch.optim.SGD([w, b], 1e-1)   如果建立了模型就用这个net.parameters()代替[w,b]，这是一个对象，他的类继承了nn.Module 
# 就会更新net里面那些grad=True的variable
 
# criterion = nn.BCEWithLogitsLoss()
# loss = criterion(out, Variable(y))
# optimizer.zero_grad()
# loss.backward()
# optimizer.step() 



# 常用的两种下降策略
#optimizer = optim.SGD(model.parameters(), lr = 0.01, momentum=0.9)
#optimizer = optim.Adam([var1, var2], lr = 0.0001)



In [ ]:
#5. 总结 np tensor variable
#定义的时候(,dtype=float)  都可以定义类型
#


In [80]:
#5.按行按列计算
print(x)
max_value, max_idx = torch.max(x, dim=1)#按行，意思就是每行操作一次，取每行最大
print('最大值：',max_value,'  最大下标:',max_idx)



tensor([[0, 0],
        [0, 0],
        [0, 0]])
最大值： tensor([0, 0, 0])   最大下标: tensor([0, 0, 0])


In [81]:
sum_x = torch.sum(x, dim=1)#按行  toch.sum(variable1==variable2)统计两个variable一维矩阵中，相同的数量
print(sum_x)

tensor([0, 0, 0])


In [82]:
#增减维度
x = torch.randn(3, 2)
print('原维度',x.shape)
x = x.unsqueeze(0) # 在第一维增加

print('增加维度:',x.shape)
x = x.squeeze()#减少维度只有1的维度，如果填入数，就指定下标的删除
print('减少维度',x.shape)

原维度 torch.Size([3, 2])
增加维度: torch.Size([1, 3, 2])
减少维度 torch.Size([3, 2])


In [83]:
#重排列
x = torch.randn(3, 2)
x = x.permute(1, 0) # permute 可以重新排列 tensor 的维度
print(x.shape)

torch.Size([2, 3])


In [87]:
x = x.transpose(0, 1)  # transpose 交换 tensor 中的两个维度
print('交换维度:',x.shape)


交换维度: torch.Size([4, 3])


In [88]:
x = torch.randn(3, 2)

#reshape操作
x = x.view(-1) # -1 表示任意的大小，5 表示第二维变成 5
print('第二维reshape:',x.shape)

第二维reshape: torch.Size([6])


In [91]:
#6.变量之间计算
x = torch.randn(3, 4)
y = torch.randn(3, 4)
z = x + y
print('求和:',z)
#如果是tensorflow，则要run才能运行

#批量赋值
print('修改前:','\n',x)
x[1:3, 1:3] = 2 #1到2的下标
print('修改后:','\n',x)



求和: tensor([[ 0.3717, -0.7831,  0.8105, -2.9360],
        [ 0.0410, -2.0129, -1.9873, -0.8350],
        [ 0.6374,  0.9576, -0.1994,  0.3087]])
修改前: 
 tensor([[ 1.0996, -0.3549,  0.3767, -1.2068],
        [-0.5463, -1.9779, -1.6327, -0.4493],
        [-0.5359, -0.1588, -0.3218, -0.1045]])
修改后: 
 tensor([[ 1.0996, -0.3549,  0.3767, -1.2068],
        [-0.5463,  2.0000,  2.0000, -0.4493],
        [-0.5359,  2.0000,  2.0000, -0.1045]])
